<?php
/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * Addresses a single cell or multiple cells
 * in a HBase table by column family and optionally
 * a column qualifier and timestamp
 */
class TColumn extends TBase
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'family',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'qualifier',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        3 => array(
            'var' => 'timestamp',
            'isRequired' => false,
            'type' => TType::I64,
        ),
    );

    /**
     * @var string
     */
    public $family = null;
    /**
     * @var string
     */
    public $qualifier = null;
    /**
     * @var int
     */
    public $timestamp = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName()
    {
        return 'TColumn';
    }


    public function read($input)
    {
        return $this->_read('TColumn', self::$_TSPEC, $input);
    }


    public function write($output)
    {
        return $this->_write('TColumn', self::$_TSPEC, $output);
    }

}
