<?php
/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * Used to perform Get operations on a single row.
 * 
 * The scope can be further narrowed down by specifying a list of
 * columns or column families.
 * 
 * To get everything for a row, instantiate a Get object with just the row to get.
 * To further define the scope of what to get you can add a timestamp or time range
 * with an optional maximum number of versions to return.
 * 
 * If you specify a time range and a timestamp the range is ignored.
 * Timestamps on TColumns are ignored.
 */
class TGet extends TBase
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'row',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'columns',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::STRUCT,
            'elem' => array(
                'type' => TType::STRUCT,
                'class' => '\TColumn',
                ),
        ),
        3 => array(
            'var' => 'timestamp',
            'isRequired' => false,
            'type' => TType::I64,
        ),
        4 => array(
            'var' => 'timeRange',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\TTimeRange',
        ),
        5 => array(
            'var' => 'maxVersions',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        6 => array(
            'var' => 'filterString',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        7 => array(
            'var' => 'attributes',
            'isRequired' => false,
            'type' => TType::MAP,
            'ktype' => TType::STRING,
            'vtype' => TType::STRING,
            'key' => array(
                'type' => TType::STRING,
            ),
            'val' => array(
                'type' => TType::STRING,
                ),
        ),
        8 => array(
            'var' => 'authorizations',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\TAuthorization',
        ),
    );

    /**
     * @var string
     */
    public $row = null;
    /**
     * @var \TColumn[]
     */
    public $columns = null;
    /**
     * @var int
     */
    public $timestamp = null;
    /**
     * @var \TTimeRange
     */
    public $timeRange = null;
    /**
     * @var int
     */
    public $maxVersions = null;
    /**
     * @var string
     */
    public $filterString = null;
    /**
     * @var array
     */
    public $attributes = null;
    /**
     * @var \TAuthorization
     */
    public $authorizations = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName()
    {
        return 'TGet';
    }


    public function read($input)
    {
        return $this->_read('TGet', self::$_TSPEC, $input);
    }


    public function write($output)
    {
        return $this->_write('TGet', self::$_TSPEC, $output);
    }

}
