<?php
/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class THBaseService_getScannerRows_args extends TBase
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'scannerId',
            'isRequired' => true,
            'type' => TType::I32,
        ),
        2 => array(
            'var' => 'numRows',
            'isRequired' => false,
            'type' => TType::I32,
        ),
    );

    /**
     * the Id of the Scanner to return rows from. This is an Id returned from the openScanner function.
     * 
     * @var int
     */
    public $scannerId = null;
    /**
     * number of rows to return
     * 
     * @var int
     */
    public $numRows = 1;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName()
    {
        return 'THBaseService_getScannerRows_args';
    }


    public function read($input)
    {
        return $this->_read('THBaseService_getScannerRows_args', self::$_TSPEC, $input);
    }


    public function write($output)
    {
        return $this->_write('THBaseService_getScannerRows_args', self::$_TSPEC, $output);
    }

}
