<?php
/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class THBaseService_mutateRow_args extends TBase
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'table',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'trowMutations',
            'isRequired' => true,
            'type' => TType::STRUCT,
            'class' => '\TRowMutations',
        ),
    );

    /**
     * table to apply the mutations
     * 
     * @var string
     */
    public $table = null;
    /**
     * mutations to apply
     * 
     * @var \TRowMutations
     */
    public $trowMutations = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName()
    {
        return 'THBaseService_mutateRow_args';
    }


    public function read($input)
    {
        return $this->_read('THBaseService_mutateRow_args', self::$_TSPEC, $input);
    }


    public function write($output)
    {
        return $this->_write('THBaseService_mutateRow_args', self::$_TSPEC, $output);
    }

}
