<?php
/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class THBaseService_getScannerResults_args extends TBase
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'table',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'tscan',
            'isRequired' => true,
            'type' => TType::STRUCT,
            'class' => '\TScan',
        ),
        3 => array(
            'var' => 'numRows',
            'isRequired' => false,
            'type' => TType::I32,
        ),
    );

    /**
     * the table to get the Scanner for
     * 
     * @var string
     */
    public $table = null;
    /**
     * the scan object to get a Scanner for
     * 
     * @var \TScan
     */
    public $tscan = null;
    /**
     * number of rows to return
     * 
     * @var int
     */
    public $numRows = 1;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName()
    {
        return 'THBaseService_getScannerResults_args';
    }


    public function read($input)
    {
        return $this->_read('THBaseService_getScannerResults_args', self::$_TSPEC, $input);
    }


    public function write($output)
    {
        return $this->_write('THBaseService_getScannerResults_args', self::$_TSPEC, $output);
    }

}
