<?php
/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class TTimeRange extends TBase
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'minStamp',
            'isRequired' => true,
            'type' => TType::I64,
        ),
        2 => array(
            'var' => 'maxStamp',
            'isRequired' => true,
            'type' => TType::I64,
        ),
    );

    /**
     * @var int
     */
    public $minStamp = null;
    /**
     * @var int
     */
    public $maxStamp = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName()
    {
        return 'TTimeRange';
    }


    public function read($input)
    {
        return $this->_read('TTimeRange', self::$_TSPEC, $input);
    }


    public function write($output)
    {
        return $this->_write('TTimeRange', self::$_TSPEC, $output);
    }

}
